MelodyRoadAnalyticsBundle_globalGraphique: 
    pattern: /{d1/{d2}/global/graphique/month
    defaults: { _controller: "MelodyRoadAnalyticsBundle:Analytics:globalGraphique" }
    options:
        analytics: false
        secure_analytics: true

MelodyRoadAnalyticsBundle_globalYearGraphique: 
    pattern: /{month}/{year}/global/graphique/year
    defaults: { _controller: "MelodyRoadAnalyticsBundle:Analytics:globalGraphiqueSinceOneYear" }
    requirements:
        day: \d+
        month: \d+
        year: \d+
    options:
        analytics: false
        secure_analytics: true