MelodyRoadAnalyticsBundle_loginImport:
    resource: "@MelodyRoadAnalyticsBundle/Resources/config/routing/login.yml"
    prefix: /analytics

MelodyRoadAnalyticsBundle_dashboardImport:
    resource: "@MelodyRoadAnalyticsBundle/Resources/config/routing/dashboard.yml"
    prefix: /

MelodyRoadAnalyticsBundle_analyticsImport:
    resource: "@MelodyRoadAnalyticsBundle/Resources/config/routing/analytics.yml"
    prefix: /analytics