services:
    melody_road_analytics.parameters_manager:
        class: Melody\RoadAnalyticsBundle\ParametersManager\ParametersManager

    melody_road_analytics.visitor_request:
        class: Melody\RoadAnalyticsBundle\Counter\Counter
        arguments: [@router, @request, @doctrine.orm.entity_manager]
        scope: request
        tags:
            - { name: kernel.event_listener, priority: -255, event: kernel.controller, method: visitorRequest }

    melody_road_analytics.is_authentificated:
        class: Melody\RoadAnalyticsBundle\Secure\SecureRoad
        arguments: [@router, @request, @session, %melody_road_analytics_login%, %melody_road_analytics_pwd%]
        scope: request
        tags:
            - { name: kernel.event_listener, priority: -255, event: kernel.request, method: isSecuredRoad }